### PR TITLE
add PR template, using the same one as sensu-plugin

### PR DESCRIPTION
**Pull request by barryorourke**

### CODE REVIEW

**Comment by majormoses** [comment]
I think you probably want to base it off the skel as that one has not been updated.

**Comment by barryorourke** [comment]
@majormoses There's a lot of stuff in the one from skel that doesn't really apply here, which is why I opted to use the same one as sensu-plugin.

Would this be a good time for us to come up with an updated one that we can apply to both sensu-plugin and sensu-plugin-python?

**Comment by majormoses** [comment]
yup I think we could come up with something a bit more library centric. There will be differences between flake8/pep8 vs rubocop etc but essentially they should have the same basic things.

**Comment by barryorourke** [comment]
I've updated this to use a modified version of the template from sensu-plugins-skel as a base. I'm not entirely sure what else we can add to it at the moment.

**Pull request merged**
