### PR TITLE
[WIP] Refactor for testing & increase test coverage

### PR DESCRIPTION
**Pull request by absolutejam**
Just wanted to add a PR with running updates to test coverage I push. Might get rebased and squashed along the way. I have limited coverage with the inbuilt `unittest` module (Runs via. nose for ease of use), and I'm aiming for 100% because I know there are parts I've been unable to manually test.

Currently, I've replaced `__init__` with `run` as it's making life waaaay easier when testing, but I can change this at the end if required.

### CODE REVIEW

**Comment by absolutejam** [comment]
43% coverage. I'm getting closer...

**Comment by absolutejam** [comment]
Also, I changed all of the tests to use `pytest` because it's more straight-forward and readable. This adds an extra dev dependency (Not yet documented), but I think it's worth it in the long run.

When I'm satisfied with the handler, I'll move onto check plugin, and also write up some example tests for plugin developers (eg. testing args).

The last commit has the changes that move the `__init__` logic to `run`, and there's a class variable called `autorun` that can be overridden before instantiation, for testing. This is how the Ruby plugin does it.

**Comment by absolutejam** [comment]
Ensure #45 gets included in test coverage

**Comment by barryorourke** [comment]
closed due to inactivity

**Pull request closed without merging**
