### PR TITLE
[DISCUSSION] Merge feat/handler_support

### PR DESCRIPTION
**Pull request by absolutejam**
Alright, it took me a little while but I converted the Ruby version. **Disclaimer:** I am not a developer, so if this code eats your infrastructure and runs over you dog, don't blame me.

This is working from my rough tests, barring one big known flaw at the moment! Currently `utils/__init__.py` contains the `config_files()` function which scrapes local config files, for use in configuring handlers - However, this only looks in `/etc/sensu/config.json` and `/etc/sensu/conf.d/*.json` at the minute.

In my Sensu setup, I have an `/etc/sensu/handlers` directory which is configured by passing in `-e /etc/sensu/handlers` to `sensu-server`, which would mean all of my handler configs would be missed (Although, I'm not sure why the Ruby `sensu-plugin` isn't missing the settings?).

I was wondering what the best method of including necessary directories is, as if we just hard-coded some directory paths, it could bite some unsuspecting users in the arse (Violates POLA), but alternatively, including `/etc/sensu/**/.json` could be dangerous or cause configs to be overwritten. The ideal situation would be to see which paths Sensu is currently using, without having to scrape the process tree.

Any ideas?

### CODE REVIEW

**Comment by absolutejam** [comment]
Also, is there any way to merge those commits on GitHub, or should I merge and re-push? I was kinda working my way through it an committing as I went.

**Comment by barryorourke** [comment]
I've had a look at the way that the the sensu_plugin ruby gem handles the scraping of local configuration files;

If there is a `SENSU_CONFIG_FILES` environmental variable containing colon separated list of paths it'll use that, otherwise it'll use  `/etc/sensu/config.json` and every directory in `/etc/sensu/conf.d/**/*.json`. I's be happy with us just replicating that for the time being.

Don't worry about merging all the commits together, I suspect we'll need a few more to get everything to pass tests anyway.

**Comment by absolutejam** [comment]
Yeah, I left those in there, but when I tested the existence of `SENSU_CONFIG_FILES` env var against my setup, they seemed to be missing - Are they standard?

**Comment by barryorourke** [comment]
`SENSU_CONFIG_FILES` is an optional setting that you can use to override the defaults, it's not set as standard.

I'm actually quite confused as to how your server is reading configuration from /etc/sensu/handlers without having the variable set.

**Comment by barryorourke** [comment]
The next stage in getting this merged into master is to sort out the testing.

I'm happy to take care of this for you if you like? to do so I'll need to fork your fork, make the changes and then submit a new pull request. That way you still get kudos for all the hard work you've done :)

Would you like me to do it, or would you like to give it a shot yourself? You'll need access to machines running python 2.7, 3.4, 3.5 & 3.6 to fully test.

**Comment by absolutejam** [comment]
Literally don't think I could get it any better for Travis :sweat_smile:

**Comment by barryorourke** [comment]
As discussed on slack, I'm happy to merge this into master and then drop the coverage percentage slightly, with the intention of writing some more tests as a separate issue.

**Pull request merged**
